<?php


namespace AppsLab\Acl\Tests;


use AppsLab\Acl\YetAnotherAlcBaseServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withFactories(__DIR__.'/../databases/factories');
    }

    protected function getPackageProviders($app)
    {
        return  [
            YetAnotherAlcBaseServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testdb');
        $app['config']->set('database.connections.testdb',[
            'driver' => 'sqlite',
            'database' => ':memory'
        ]);
    }
}